/* eslint-disable */
/**
 * This file was automatically generated by @algorandfoundation/algokit-client-generator.
 * DO NOT MODIFY IT BY HAND.
 * requires: @algorandfoundation/algokit-utils: ^7
 */

// TODO: This file needs to be regenerated with the new algokit-utils types
// Temporarily stubbed out until the algokit-client-generator is updated

export const APP_SPEC = {} as any
export class TestingAppFactory {
  constructor(_params: any) {}
  send = {
    create: {
      bare: async (_params: any) => ({} as any),
    },
  }
  createTransaction = {
    create: {
      bare: async (_params: any) => ({} as any),
    },
  }
}
