/* eslint-disable */
/**
 * This file was automatically generated by @algorandfoundation/algokit-client-generator.
 * DO NOT MODIFY IT BY HAND.
 * requires: @algorandfoundation/algokit-utils: ^7
 *
 * TODO: Regenerate this file using the updated algokit client generator
 * that is compatible with the new @algorandfoundation/algokit-utils version.
 */

// Stub exports to satisfy imports
export class VotingRoundAppClient {
  constructor(_params: any) {}
  state = {
    global: {
      getAll: async () => ({
        metadataIpfsCid: { asString: () => '' }
      })
    }
  }
}
