name: Pull Request

on:
  push:
    branches:
      - main
      - alpha
      - ci/pr-workflow-to-main
  pull_request:
    branches:
      - main
      - alpha

permissions:
  contents: read
  checks: write

jobs:
  pull_request:
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-ci.yml@main
    with:
      node-version: 20.x
      working-directory: .
      run-commit-lint: true
      run-build: true
      pre-test-script: |
        pipx install algokit
        algokit localnet start
        npx --yes wait-on tcp:4001 -t 30000
      audit-script: |
        npm run audit

  check_docs:
    uses: algorandfoundation/algokit-shared-config/.github/workflows/check-docs.yml@main
