name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-ci.yml@main
    with:
      run-commit-lint: true
      run-build: true
      audit-script: npm run audit
      install-algokit: true

  check_docs:
    uses: algorandfoundation/algokit-shared-config/.github/workflows/check-docs.yml@main

