name: Pull Request

on:
  push:
    branches:
      - ci/reusable-pull-request
  pull_request:
    branches:
      - main
      - alpha
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  pull_request:
    uses: algorandfoundation/algokit-shared-config/.github/workflows/on-pull-request.yml@feat/pr-workflow
    with:
      project-type: node
      node-version: 20.x
      working-directory: .
      audit-level: moderate
      pre-test-script: |
        pipx install algokit
        algokit localnet start
        npx --yes wait-on tcp:4001 -t 30000
      skip-commit-lint: false


  ## Do we need to check docs here?
