name: Prod Publish

on:
  workflow_dispatch:

jobs:
  prod_release:
    name: Prod release
    uses: algorandfoundation/algokit-shared-config/.github/workflows/prod-release.yml@ci/reusable-release
    secrets:
      BOT_ID: ${{ secrets.BOT_ID }}
      BOT_SK: ${{ secrets.BOT_SK }}
