name: Publish

on:
  push:
    branches:
      - main
      - release
      - alpha
  workflow_dispatch:

concurrency: release

permissions:
  pages: write
  contents: write
  id-token: write

jobs:
  ci:
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-ci.yml@main
    with:
      node-version: 20.x
      working-directory: .
      run-commit-lint: true
      run-build: true
      pre-test-script: |
        pipx install algokit
        algokit localnet start
        npx --yes wait-on tcp:4001 -t 30000

  build:
    name: Build
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-build-zip.yml@ci/reusable-release
    needs:
      - ci
    with:
      build-path: dist
      artifact-name: package

  generate_and_publish_docs:
    needs:
      - ci
    name: Build and Publish Docs
    uses: algorandfoundation/algokit-shared-config/.github/workflows/build-and-publish-docs.yml@ci/reusable-release

  release:
    name: Release
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-release.yml@ci/reusable-release
    needs:
      - build

    with:
      dry-run: true
    secrets:
      BOT_ID: ${{ secrets.BOT_ID }}
      BOT_SK: ${{ secrets.BOT_SK }}
