name: Publish

on:
  push:
    branches:
      - main
      - release
      - alpha
  workflow_dispatch:

concurrency: release

jobs:
  ci:
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-ci.yml@main
    with:
      node-version: 20.x
      working-directory: .
      run-commit-lint: true
      run-build: true
      pre-test-script: |
        pipx install algokit
        algokit localnet start
        npx --yes wait-on tcp:4001 -t 30000
      audit-script: |
        npm run audit

  build:
    name: Build
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-build-zip.yml@ci/reusable-release
    # needs:
    #   - ci
    with:
      node-version: 20.x
      build-path: dist
      artifact-name: package

  release:
    name: Release
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-release.yml@ci/reusable-release
    needs:
      - build
    secrets:
      BOT_ID: ${{ secrets.BOT_ID }}
      BOT_SK: ${{ secrets.BOT_SK }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
